# SPDX-FileCopyrightText: 2020 Benedict Harcourt
#
# SPDX-License-Identifier: BSD-2-Clause

env:
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
